#!/usr/bin/env bash
# Monthly cross-project dead-code sweep.
#
# Runs `npm run lint:dead` in every project under the projects root that has a
# `lint:dead` script (see setup-knip-fallow.sh), and writes one dated report.
# It does NOT auto-fix anything: the point is to surface dead code that has
# accumulated since the last sweep, not to let a cron job delete your code.
#
# Cron (06:00 on the 1st):
#   0 6 1 * * $HOME/.claude/scripts/monthly-lint-dead-sweep.sh
#
# Configuration, all optional:
#   PROJECTS_DIR   where to look for projects (default ~/Projects). Scans one and
#                  two levels deep, so grouped repos (<org>/<repo>) are covered.
#   REPORT_DIR     where the report lands (default ~/notes)
#   TIMEOUT_SECS   per-project cap (default 120)
#   NOTIFY_CMD     optional hook: a command taking (title, body), called only when
#                  a project fails. Unset → no notification, and never an error.
#                  Point it at your own notifier (ntfy curl, mail, a Signal CLI…).
set -uo pipefail

DATE=$(date +%Y-%m-%d)
PROJECTS_DIR="${PROJECTS_DIR:-$HOME/Projects}"
REPORT_DIR="${REPORT_DIR:-$HOME/notes}"
TIMEOUT_SECS="${TIMEOUT_SECS:-120}"
NOTIFY_CMD="${NOTIFY_CMD:-}"
REPORT="$REPORT_DIR/lint-dead-sweep-$DATE.md"

mkdir -p "$REPORT_DIR"
BODY=$(mktemp)
trap 'rm -f "$BODY"' EXIT

CLEAN=0
FAIL=0
FAILED_PROJECTS=()

for dir in "$PROJECTS_DIR"/*/ "$PROJECTS_DIR"/*/*/; do
  [[ -d "$dir" ]] || continue
  [[ -f "$dir/package.json" ]] || continue
  grep -q '"lint:dead"' "$dir/package.json" 2>/dev/null || continue

  name=$(basename "$dir")
  echo "==> $name" >&2

  pushd "$dir" >/dev/null || continue
  if output=$(timeout "$TIMEOUT_SECS" npm run lint:dead --silent 2>&1); then
    printf '## %s — CLEAN\n\n' "$name" >> "$BODY"
    CLEAN=$((CLEAN + 1))
  else
    rc=$?
    {
      printf '## %s — FAILED (exit %s)\n\n' "$name" "$rc"
      printf '```\n%s\n```\n\n' "$(echo "$output" | tail -40)"
    } >> "$BODY"
    FAIL=$((FAIL + 1))
    FAILED_PROJECTS+=("$name")
  fi
  popd >/dev/null || true
done

# Header + summary first, then the per-project body. Built in this order rather
# than prepended afterwards, so the report shape isn't coupled to a line count.
{
  echo "# lint:dead sweep — $DATE"
  echo
  echo "Auto-generated by \`monthly-lint-dead-sweep.sh\`. Scans \`$PROJECTS_DIR\`"
  echo "(one and two levels deep) for any project with an \`npm run lint:dead\` script."
  echo
  echo "## Summary"
  echo
  echo "- Clean: $CLEAN"
  echo "- Failing: $FAIL"
  if (( FAIL > 0 )); then
    echo "- Failing projects: ${FAILED_PROJECTS[*]}"
  fi
  echo
  echo "---"
  echo
  cat "$BODY"
} > "$REPORT"

echo "==> Report: $REPORT"
echo "    Clean: $CLEAN  Failing: $FAIL"

# Optional notification hook. Absent or broken is a skip, never a failed sweep.
if (( FAIL > 0 )) && [[ -n "$NOTIFY_CMD" ]]; then
  "$NOTIFY_CMD" "lint:dead sweep — $FAIL failures" \
    "Projects: ${FAILED_PROJECTS[*]}. Report: $REPORT" || true
fi
